export const trip = {
  name: "Japan Family Trip 2026",
  dates: "7 - 13 ธันวาคม 2569",
  members: ["Toon", "Gus", "Pun", "Pae"],
  budget: 96000,
  spent: 62000,
  departureDate: new Date("2026-12-07"),
};

export const itinerary = [
  {
    day: "Day 1",
    date: "7 Dec 2026",
    title: "Arrival + Hakata + Shrine Walk",
    emoji: "🛬",
    entries: [
      { time: "07:35", detail: "ถึง Fukuoka Airport (FUK) จากไฟลต์ VN356" },
      { time: "08:10", detail: "นั่ง Airport Bus เข้า Hakata และฝากกระเป๋า" },
      { time: "09:30", detail: "Exchange JR Pass และจัดการตั๋วเดินทางหลัก" },
      { time: "11:00", detail: "แวะ Tochoji Temple และ Kushida Shrine" },
      { time: "13:00", detail: "มื้อกลางวันย่าน Hakata" },
      { time: "16:30", detail: "เดินเล่น Canal City" },
      { time: "19:00", detail: "มื้อเย็นย่าน Tenjin แล้วกลับที่พัก" },
    ],
  },
  {
    day: "Day 2",
    date: "8 Dec 2026",
    title: "Move Hotel + Nanzoin",
    emoji: "🛕",
    entries: [
      { time: "09:30", detail: "เช็กเอาต์โรงแรมเดิมและย้ายไป One's Hotel Fukuoka" },
      { time: "11:00", detail: "Airport Line ไป Hakata แล้วต่อรถไฟไป Nanzoin" },
      { time: "12:30", detail: "เที่ยว Nanzoin Temple (พระนอน)" },
      { time: "15:30", detail: "กลับเข้าเมือง แวะช้อปปิงเบาๆ" },
      { time: "18:30", detail: "Ichiran ramen" },
      { time: "20:00", detail: "เดินเล่นย่าน Yatai แล้วกลับที่พัก" },
    ],
  },
  {
    day: "Day 3",
    date: "9 Dec 2026",
    title: "Dazaifu Day Trip",
    emoji: "⛩️",
    entries: [
      { time: "08:00", detail: "ออกจากโรงแรมไป Hakata Bus Center" },
      { time: "09:00", detail: "นั่งบัสไป Dazaifu" },
      { time: "10:00", detail: "เดินถนนคนเดิน + Dazaifu Tenmangu" },
      { time: "12:30", detail: "มื้อกลางวันแถว Dazaifu" },
      { time: "15:30", detail: "ขึ้นบัสกลับ Fukuoka" },
      { time: "18:00", detail: "Canal City และมื้อเย็นย่าน Tenjin" },
    ],
  },
  {
    day: "Day 4",
    date: "10 Dec 2026",
    title: "Yufuin + Kinrin Lake",
    emoji: "🌸",
    entries: [
      { time: "07:30", detail: "ออกจากที่พักไป Hakata Station" },
      { time: "09:17", detail: "รถไฟ Yufuin No Mori ออกจาก Hakata" },
      { time: "11:31", detail: "ถึง Yufuin และเริ่มเดินเที่ยวเมือง" },
      { time: "13:00", detail: "เที่ยว Yufuin Floral Village" },
      { time: "15:00", detail: "แวะ Kinrin Lake + Yunotsubo Street" },
      { time: "17:17", detail: "ขึ้นรถไฟกลับ Fukuoka" },
      { time: "19:28", detail: "ถึง Hakata และกลับโรงแรม" },
    ],
  },
  {
    day: "Day 5",
    date: "11 Dec 2026",
    title: "Aso Day Trip",
    emoji: "🌋",
    entries: [
      { time: "08:00", detail: "ออกจากที่พักและนั่ง Shinkansen ไป Kumamoto" },
      { time: "09:30", detail: "ต่อรถไฟ/บัสไป Aso" },
      { time: "11:30", detail: "ถึง Aso และขึ้นรถบัสไปจุดชมวิว Aso San" },
      { time: "13:00", detail: "เที่ยวโซนภูเขาไฟ (ขึ้นกับสภาพอากาศ)" },
      { time: "16:00", detail: "เดินทางกลับ Kumamoto และต่อกลับ Hakata" },
      { time: "20:00", detail: "ถึง Hakata และพักผ่อน" },
    ],
  },
  {
    day: "Day 6",
    date: "12 Dec 2026",
    title: "Mojiko + Karato + Kumamoto",
    emoji: "🐡",
    entries: [
      { time: "07:00", detail: "ออกจากโรงแรมไป Hakata Station" },
      { time: "07:20", detail: "นั่งรถไฟไป Mojiko" },
      { time: "09:30", detail: "ข้ามไป Karato Fish Market เดินเล่นและกินซูชิ" },
      { time: "12:30", detail: "เดินทางกลับฝั่ง Mojiko" },
      { time: "13:30", detail: "ขึ้น Shinkansen ไป Kumamoto" },
      { time: "16:00", detail: "เดินเล่น Josaien / Shimotori Shopping Arcade" },
      { time: "20:00", detail: "กลับที่พัก" },
    ],
  },
  {
    day: "Day 7",
    date: "13 Dec 2026",
    title: "Airport + Fly Home",
    emoji: "🛫",
    entries: [
      { time: "05:30", detail: "เช็กเอาต์และเดินทางไปสนามบิน Fukuoka" },
      { time: "10:00", detail: "ไฟลต์ VN357: FUK → HAN" },
      { time: "12:55", detail: "ถึง Hanoi และรอทรานซิต" },
      { time: "15:50", detail: "ไฟลต์ VN619: HAN → BKK" },
      { time: "17:55", detail: "ถึงกรุงเทพฯ และเดินทางกลับบ้าน" },
    ],
  },
];

export const expenses = [
  { category: "Flight", estimate: 62000, actual: 62000 },
  { category: "Hotel", estimate: 15000, actual: 0 },
  { category: "Food & Dining", estimate: 8000, actual: 0 },
  { category: "Transport (JR Pass etc.)", estimate: 6000, actual: 0 },
  { category: "Activities", estimate: 5000, actual: 0 },
];

export const bookedFlights = [
  {
    direction: "Bangkok to Fukuoka",
    routeCode: "BKK → FUK",
    departLabel: "Sat 6 Dec 2026",
    arriveLabel: "Sun 7 Dec 2026",
    duration: "7h 25m",
    transit: "Transit at Hanoi (HAN) 1h 50m",
    layoverDuration: "1h 50m",
    bookingRef: "PNR: VN8FUK26",
    segments: [
      {
        route: "BKK 22:10 → HAN 00:05 (+1)",
        flightNo: "VN616",
        aircraft: "Airbus A321",
        seat: "Toon 24A · Gus 24B · Pun 24C · Pae 24D",
        from: { code: "BKK", city: "Bangkok", time: "22:10" },
        to: { code: "HAN", city: "Hanoi", time: "00:05" },
        duration: "3h 55m",
      },
      {
        route: "HAN 01:55 → FUK 07:35",
        flightNo: "VN356",
        aircraft: "Airbus A321",
        seat: "Toon 18A · Gus 18B · Pun 18C · Pae 18D",
        from: { code: "HAN", city: "Hanoi", time: "01:55" },
        to: { code: "FUK", city: "Fukuoka", time: "07:35" },
        duration: "5h 40m",
      },
    ],
    flow: ["Thailand", "Hanoi", "Fukuoka"],
  },
  {
    direction: "Fukuoka to Bangkok",
    routeCode: "FUK → BKK",
    departLabel: "Mon 14 Dec 2026",
    arriveLabel: "Mon 14 Dec 2026",
    duration: "9h 55m",
    transit: "Transit at Hanoi (HAN) 2h 55m",
    layoverDuration: "2h 55m",
    bookingRef: "PNR: VN8BKK26",
    segments: [
      {
        route: "FUK 10:00 → HAN 12:55",
        flightNo: "VN357",
        aircraft: "Airbus A321",
        seat: "Toon 16A · Gus 16B · Pun 16C · Pae 16D",
        from: { code: "FUK", city: "Fukuoka", time: "10:00" },
        to: { code: "HAN", city: "Hanoi", time: "12:55" },
        duration: "2h 55m",
      },
      {
        route: "HAN 15:50 → BKK 17:55",
        flightNo: "VN619",
        aircraft: "Airbus A321",
        seat: "Toon 21A · Gus 21B · Pun 21C · Pae 21D",
        from: { code: "HAN", city: "Hanoi", time: "15:50" },
        to: { code: "BKK", city: "Bangkok", time: "17:55" },
        duration: "2h 05m",
      },
    ],
    flow: ["Fukuoka", "Hanoi", "Thailand"],
  },
];

export const defaultChecklist = [
  { label: "Passport", done: true },
  { label: "JR Pass booking", done: true },
  { label: "Travel insurance", done: false },
  { label: "Universal Studios tickets", done: false },
  { label: "Hotel booking", done: false },
  { label: "Airport bus / transport plan", done: false },
  { label: "Pocket WiFi / SIM card", done: false },
  { label: "Currency exchange (JPY)", done: false },
];
